### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by Madhuri97** [Madhuri97/project-1-105#3]
**Terminal:**
![Screenshot (324)](https://user-images.githubusercontent.com/55680886/79371232-a9802100-7f71-11ea-83f0-08c316554115.png)
**Flask Main Page:**
![Screenshot (321)](https://user-images.githubusercontent.com/55680886/79371252-b3098900-7f71-11ea-80ec-d47d6d11aba1.png)
**Registration Page:**
![Screenshot (322)](https://user-images.githubusercontent.com/55680886/79371265-b9980080-7f71-11ea-912c-7bb631cbe89a.png)
**Data Page:**
![Screenshot (323)](https://user-images.githubusercontent.com/55680886/79371278-bf8de180-7f71-11ea-8f6b-9ea518278c72.png)

**Comment by ChaitanyaPuritipati** [comment]
You also need to put the screenshot of details being shown on the flask server i.e command line. Rest everything is fine

**Comment by Madhuri97** [comment]
**Output with the name:**
![Screenshot (327)](https://user-images.githubusercontent.com/55680886/79429738-927b1680-7fe5-11ea-831e-e66708d056a0.png)

**Comment by ChaitanyaPuritipati** [comment]
Good work
