### ISSUE TITLE
ORM with SQLAlchemy

### ISSUE THREAD

**Issue by Madhuri97** [Madhuri97/project-1-105#4]
**Password encryption**
![Screenshot (337)](https://user-images.githubusercontent.com/55680886/79654239-d5004700-81cf-11ea-870d-b72e38a51c08.png)
**Alert boxes
![Screenshot (333)](https://user-images.githubusercontent.com/55680886/79655145-18f34c00-81d0-11ea-9e1d-16c11efbd3b1.png)
 for registration**
![Screenshot (332)](https://user-images.githubusercontent.com/55680886/79654547-ecd7cb00-81cf-11ea-93fb-63cb7ed0f84f.png)
**Terminal**
![Screenshot (334)](https://user-images.githubusercontent.com/55680886/79655448-2f99a300-81d0-11ea-9ac5-e1960f779c98.png)

**Comment by ChaitanyaPuritipati** [comment]
Good work. Nice to see that you have used alert colour according to the purpose i.e green for success and red for error. Encrypting password is a nice idea. It helps in hiding the information from the admin as well and maintains the user data secured. You can merge the branch and start working on authentication
